// Mock data for demo mode (when Supabase is not configured)

export const mockGuests = [
  {
    id: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    axisEmail: 'john.doe@axis.com',
    reportingLevel1: 'APAC',
    reportingLevel2: 'Southeast Asia',
    reportingLevel3: 'Singapore',
    function: 'Sales',
    location: 'Singapore',
    arrivalDate: '2026-03-15',
    arrivalTime: '10:30',
    arrivalFlightNumber: 'SQ123',
    arrivalAirport: 'KLIA',
    departureDate: '2026-03-18',
    departureTime: '16:00',
    departureFlightNumber: 'SQ456',
    departureAirport: 'KLIA',
    hotelCheckinDate: '2026-03-15',
    hotelCheckoutDate: '2026-03-18',
    roomType: 'Deluxe King',
    needsArrivalTransfer: true,
    needsDepartureTransfer: true,
    registrationStatus: 'confirmed' as const,
    travelType: 'International',
    version: 1,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
    deletedAt: null,
  },
  {
    id: '2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    axisEmail: 'jane.smith@axis.com',
    reportingLevel1: 'APAC',
    reportingLevel2: 'North Asia',
    reportingLevel3: 'Japan',
    function: 'Marketing',
    location: 'Tokyo',
    arrivalDate: '2026-03-14',
    arrivalTime: '08:15',
    arrivalFlightNumber: 'JL789',
    arrivalAirport: 'KLIA',
    departureDate: '2026-03-18',
    departureTime: '20:30',
    departureFlightNumber: 'JL790',
    departureAirport: 'KLIA',
    hotelCheckinDate: '2026-03-14',
    hotelCheckoutDate: '2026-03-18',
    roomType: 'Deluxe Twin',
    needsArrivalTransfer: true,
    needsDepartureTransfer: false,
    registrationStatus: 'confirmed' as const,
    travelType: 'International',
    version: 1,
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-01-14'),
    deletedAt: null,
  },
  {
    id: '3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r',
    email: 'bob.wilson@example.com',
    firstName: 'Bob',
    lastName: 'Wilson',
    axisEmail: 'bob.wilson@axis.com',
    reportingLevel1: 'APAC',
    reportingLevel2: 'Southeast Asia',
    reportingLevel3: 'Malaysia',
    function: 'Engineering',
    location: 'Kuala Lumpur',
    arrivalDate: '2026-03-15',
    arrivalTime: null,
    arrivalFlightNumber: null,
    arrivalAirport: null,
    departureDate: '2026-03-17',
    departureTime: null,
    departureFlightNumber: null,
    departureAirport: null,
    hotelCheckinDate: '2026-03-15',
    hotelCheckoutDate: '2026-03-17',
    roomType: 'Standard',
    needsArrivalTransfer: false,
    needsDepartureTransfer: false,
    registrationStatus: 'pending' as const,
    travelType: 'Local',
    version: 1,
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date('2025-01-16'),
    deletedAt: null,
  },
  {
    id: '4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s',
    email: 'alice.chen@example.com',
    firstName: 'Alice',
    lastName: 'Chen',
    axisEmail: 'alice.chen@axis.com',
    reportingLevel1: 'APAC',
    reportingLevel2: 'Greater China',
    reportingLevel3: 'Hong Kong',
    function: 'Finance',
    location: 'Hong Kong',
    arrivalDate: '2026-03-15',
    arrivalTime: '14:45',
    arrivalFlightNumber: 'CX888',
    arrivalAirport: 'KLIA',
    departureDate: '2026-03-18',
    departureTime: '11:00',
    departureFlightNumber: 'CX889',
    departureAirport: 'KLIA',
    hotelCheckinDate: '2026-03-15',
    hotelCheckoutDate: '2026-03-18',
    roomType: 'Suite',
    needsArrivalTransfer: true,
    needsDepartureTransfer: true,
    registrationStatus: 'confirmed' as const,
    travelType: 'International',
    version: 1,
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-01-17'),
    deletedAt: null,
  },
  {
    id: '5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t',
    email: 'david.kumar@example.com',
    firstName: 'David',
    lastName: 'Kumar',
    axisEmail: 'david.kumar@axis.com',
    reportingLevel1: 'APAC',
    reportingLevel2: 'South Asia',
    reportingLevel3: 'India',
    function: 'Operations',
    location: 'Mumbai',
    arrivalDate: '2026-03-14',
    arrivalTime: '22:00',
    arrivalFlightNumber: 'AI202',
    arrivalAirport: 'KLIA',
    departureDate: '2026-03-19',
    departureTime: '06:30',
    departureFlightNumber: 'AI203',
    departureAirport: 'KLIA',
    hotelCheckinDate: '2026-03-14',
    hotelCheckoutDate: '2026-03-19',
    roomType: 'Deluxe King',
    needsArrivalTransfer: true,
    needsDepartureTransfer: true,
    registrationStatus: 'confirmed' as const,
    travelType: 'International',
    version: 1,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-18'),
    deletedAt: null,
  },
];

export const mockVehicles = [
  {
    id: 'v1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
    name: 'Van A',
    type: 'van',
    capacity: 12,
    driverName: 'Ahmad',
    driverPhone: '+60 12 345 6789',
    licensePlate: 'WKL 1234',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'v2b3c4d5-e6f7-g8h9-i0j1-k2l3m4n5o6p7',
    name: 'Bus 1',
    type: 'bus',
    capacity: 40,
    driverName: 'Raj',
    driverPhone: '+60 12 987 6543',
    licensePlate: 'WKL 5678',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'v3c4d5e6-f7g8-h9i0-j1k2-l3m4n5o6p7q8',
    name: 'Sedan 1',
    type: 'sedan',
    capacity: 3,
    driverName: 'Lee',
    driverPhone: '+60 12 111 2222',
    licensePlate: 'WKL 9012',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

export const mockSchedules = [
  {
    id: 's1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
    vehicleId: 'v1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
    direction: 'arrival' as const,
    scheduleDate: new Date().toISOString().split('T')[0],
    pickupTime: '10:00',
    pickupLocation: 'KLIA Terminal 1 - Arrival Hall',
    dropoffLocation: 'Shangri-La Hotel KL',
    status: 'scheduled' as const,
    notes: 'VIP guests',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    vehicle: {
      id: 'v1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
      name: 'Van A',
      type: 'van',
      capacity: 12,
    },
    assignments: [
      {
        id: 'a1',
        guest: {
          id: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
          firstName: 'John',
          lastName: 'Doe',
          email: 'john.doe@example.com',
        },
      },
      {
        id: 'a2',
        guest: {
          id: '4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s',
          firstName: 'Alice',
          lastName: 'Chen',
          email: 'alice.chen@example.com',
        },
      },
    ],
  },
  {
    id: 's2b3c4d5-e6f7-g8h9-i0j1-k2l3m4n5o6p7',
    vehicleId: 'v2b3c4d5-e6f7-g8h9-i0j1-k2l3m4n5o6p7',
    direction: 'arrival' as const,
    scheduleDate: new Date().toISOString().split('T')[0],
    pickupTime: '14:30',
    pickupLocation: 'KLIA Terminal 2 - Arrival Hall',
    dropoffLocation: 'Shangri-La Hotel KL',
    status: 'scheduled' as const,
    notes: null,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    vehicle: {
      id: 'v2b3c4d5-e6f7-g8h9-i0j1-k2l3m4n5o6p7',
      name: 'Bus 1',
      type: 'bus',
      capacity: 40,
    },
    assignments: [
      {
        id: 'a3',
        guest: {
          id: '5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t',
          firstName: 'David',
          lastName: 'Kumar',
          email: 'david.kumar@example.com',
        },
      },
    ],
  },
  {
    id: 's3c4d5e6-f7g8-h9i0-j1k2-l3m4n5o6p7q8',
    vehicleId: 'v1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
    direction: 'departure' as const,
    scheduleDate: new Date().toISOString().split('T')[0],
    pickupTime: '18:00',
    pickupLocation: 'Shangri-La Hotel KL',
    dropoffLocation: 'KLIA Terminal 1',
    status: 'scheduled' as const,
    notes: 'Early departure',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    vehicle: {
      id: 'v1a2b3c4-d5e6-f7g8-h9i0-j1k2l3m4n5o6',
      name: 'Van A',
      type: 'van',
      capacity: 12,
    },
    assignments: [],
  },
];

export const mockAuditLogs = [
  {
    id: 'log1',
    entityType: 'guest',
    entityId: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
    action: 'create',
    changes: [
      { field: 'firstName', oldValue: null, newValue: 'John', fieldType: 'string' },
      { field: 'lastName', oldValue: null, newValue: 'Doe', fieldType: 'string' },
    ],
    changeSource: 'import' as const,
    importSessionId: 'import1',
    performedBy: 'demo-user-id',
    createdAt: new Date('2025-01-15T10:00:00'),
  },
  {
    id: 'log2',
    entityType: 'guest',
    entityId: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
    action: 'update',
    changes: [
      { field: 'registrationStatus', oldValue: 'pending', newValue: 'confirmed', fieldType: 'string' },
    ],
    changeSource: 'manual' as const,
    importSessionId: null,
    performedBy: 'demo-user-id',
    createdAt: new Date('2025-01-16T14:30:00'),
  },
];

export const mockImportSessions = [
  {
    id: 'import1',
    filename: 'axis_kickoff_2026_guests.xlsx',
    status: 'completed' as const,
    totalRows: 340,
    addedCount: 335,
    modifiedCount: 5,
    removedCount: 0,
    errorCount: 0,
    performedBy: 'demo-user-id',
    createdAt: new Date('2025-01-15T10:00:00'),
    completedAt: new Date('2025-01-15T10:05:00'),
  },
];
